Feature/#13 dm api
CDS-Mobile1/CDS-Instagram-Android pull request #18
Opened 2023-05-25 16:36 UTC by minju1459

- closed #13

## *⛳️ Work Description*
- 즐겨찾기한 유저 스토리 목록 API 서버 통신 구현
- DM 리스트 조회 API 서버 통신 구현

## *📸 Screenshot*

<img width="270" alt="스크린샷 2023-05-26 오전 1 31 56" src="https://github.com/CDS-Mobile1/CDS-Instagram-Android/assets/76741702/5bc7bfbb-9917-4ac6-b9ab-583490318661">

## *📢 To Reviewers*
- 즐겨찾기 변경 api 연결과 별 클릭 시 RV item 추가 구현하는 중입니다..!

2023-05-25 18:00 UTC, SeonHwan-Kim approved these changes
좋습니당~ 
다음에 시간이 된다면 세미나에서 배웠던 livedata도 이용해보면 좋을 것 같아용
그리고 coroutine도!!

2023-05-25 18:00 UTC, SeonHwan-Kim commented on app/src/main/java/com/sopt/instagram/data/service/DmstoryService.kt
> +    @Headers("Authorization:1")
Headers들이 반복되어 사용되고있는데 interceptor로 구현하면 좋을 것 같아용

2023-05-25 18:00 UTC, SeonHwan-Kim commented on app/src/main/java/com/sopt/instagram/ui/dm/DmActivity.kt
> +                    Snackbar.make(
snackbar는 util에 있는 showSnackbar()를 사용하면 좋을 것 같아용

2023-05-25 18:09 UTC, minju1459 commented on app/src/main/java/com/sopt/instagram/ui/dm/DmActivity.kt
> +                    Snackbar.make(
앗 잊고 있었네요.. 바로 적용하겠습니다~!

2023-05-25 18:45 UTC, b1urrrr requested changes
서버통신까지 구현하시느라 고생하셨습니다 💖
첨부해주신 스크린샷을 보니까 디엠 메시지 내용이 즐겨찾기 버튼 영역과 겹치고 있네요! 피그마를 참고해서 컴포넌트들이 겹치지 않도록 제약 설정 부탁드려요!

2023-05-25 18:45 UTC, b1urrrr commented on app/src/main/AndroidManifest.xml
> +            android:exported="true"
오 new post는 선환님 뷰인 것 같은데 혹시 true로 설정하신 이유가 있을까요?

2023-05-25 18:45 UTC, b1urrrr commented on app/src/main/java/com/sopt/instagram/data/ApiFactory.kt
> +    val dmlistService = ApiFactory.create<DmlistService>()
Service, DataSource, Repository 등은 서버 API 명세서의 도메인에 따라 분리하여 같은 도메인에 해당하는 api는 같은 파일에 작성하는 것이 더 용이할 것입니다! 앱잼에서는 그렇게 해보시는 걸 추천 드립니당

2023-05-25 18:45 UTC, b1urrrr commented on app/src/main/java/com/sopt/instagram/ui/dm/GetLIstAdapter.kt
> +                    .into(btnDmMsgPhoto)
프로필 이미지는 원형인 것 같은데, Glide나 Coil은 이미지 transformation 기능을 지원하고 있습니다! 이 기능을 이용해서 이미지가 원으로 적용되도록 구현해보시는 걸 추천 드려요!

2023-05-25 18:55 UTC, minju1459 commented on app/src/main/AndroidManifest.xml
> +            android:exported="true"
앗 잠시 바꿔놓았는데 까먹었네요..! 감사합니당

2023-05-25 18:55 UTC, minju1459 commented on app/src/main/java/com/sopt/instagram/data/ApiFactory.kt
> +    val dmlistService = ApiFactory.create<DmlistService>()
넵 !! 앱잼 전까지 꼭 미리 마스터해보겠습니당

2023-05-26 04:03 UTC, minju1459 commented on app/src/main/java/com/sopt/instagram/ui/dm/GetLIstAdapter.kt
> +                    .into(btnDmMsgPhoto)
좋은 기능 감사합니다 !! 적용해보겠습니다 ! (엇 쓰다가 갑자기 잠들었네요..)

2023-05-26 05:54 UTC, b1urrrr approved these changes
LGTM 고생하셨습니다 💖👍

2023-05-26 06:03 UTC, merged