Feature/#5 dm UI
CDS-Mobile1/CDS-Instagram-Android pull request #9
Opened 2023-05-22 18:57 UTC by minju1459

- #5 

## *⛳️ Work Description*
- UI 대략적인 구현
- 서버 통신 주변 멤도는중

## *📸 Screenshot*
<img width="275" alt="스크린샷 2023-05-23 오전 3 43 36" src="https://github.com/CDS-Mobile1/CDS-Instagram-Android/assets/76741702/75067d29-3122-4e51-a48d-35f2239cfc9d">

## *📢 To Reviewers*
- 리싸이클러뷰 어댑터를 서버 통신과 같이 하려하니 아직 연결이 안돼서 
story와 message 부분이 아직 안보입니다
- commit 메세지가 왜 저럴까요 , commit 자주하겠습니다..
- 스토리뷰 동그라미 ui가 xml (selector 이용) 을 재사용한다는게 맞나요??

2023-05-23 08:03 UTC, b1urrrr requested changes
ListAdapter까지 깔쌈하게 활용하셨네요!
UI 구현하시느라 고생 많으셨습니다 💖

2023-05-23 08:03 UTC, b1urrrr commented on app/src/androidTest/java/com/sopt/instagram/ExampleInstrumentedTest.kt
> +import org.junit.Assert.* // ktlint-disable no-wildcard-imports
제가 다 해놨어야 했는데... 고생하셨습니다 🤣

2023-05-23 08:03 UTC, b1urrrr commented on app/src/main/AndroidManifest.xml
> +            android:name=".ui.main.dm.DmActivity"
MainActivity는 선환님이 작업하고 계신 뷰이기 때문에 DmAcitivty를 위한 <activity> 태그를 따로 하나 추가해주세요!

![그림1](https://github.com/CDS-Mobile1/CDS-Instagram-Android/assets/70993562/ac4b4572-9d65-4ce4-917f-57e1283bd381)

참고로 `우클릭 > New > Activity > Empty Views Activity`를 활용하시면 안드로이드 스튜디오에서 일괄적으로 새로운 액티비티에 대해 AndroidManifest 태그 추가, xml 파일 생성, kotlin 파일 생성 등의 처리를 해주어 편리합니다 👍

2023-05-23 08:03 UTC, b1urrrr commented on app/src/main/java/com/sopt/instagram/ui/main/dm/GetStoryAdapter.kt
> +    GetStoryCallback,
ListAdapter 활용 너무 좋습니다 🤭

2023-05-23 08:03 UTC, b1urrrr commented on app/src/main/java/com/sopt/instagram/ui/main/dm/GetStoryAdapter.kt
> +            }
`areItemsTheSame` 함수는 `areContentsTheSame` 함수를 호출하기 전에 미리 `oldItem`과 `newItem`이 동일한 아이템인지 간단하게 비교하는 함수이기 때문에 `hashCode()` 값을 비교하는 것보다는 아이템의 고유한 값(EX. `memberId`)을 비교해 주는 것이 적합할 것 같습니다!

2023-05-23 08:03 UTC, b1urrrr commented on app/src/main/java/com/sopt/instagram/ui/main/dm/GetStoryAdapter.kt
> +    }
`companion object`는 클래스의 최하단에 위치하는 것이 관례입니다.
[안드로이드 공식 문서](https://developer.android.com/kotlin/common-patterns#companion)와 [공식 문서에서 샘플로 제공하고 있는 sunflower 프로젝트의 코드](https://github.com/android/sunflower/blob/cdb3b2b5938ec0934ecaee800754c8e462c2d85c/app/src/main/java/com/google/samples/apps/sunflower/data/UnsplashRepository.kt#L35)를 참고해주세요!

2023-05-23 08:03 UTC, b1urrrr commented on app/src/main/res/drawable/btn_dm_star.xml
> +    <item android:state_pressed="false" android:drawable="@drawable/ic_dm_star_unpress"/>
`state_pressed` 속성은 뷰가 클릭되었을 때 나타나는 일시적인 UI를 구현할 때 주로 사용됩니다! 현재와 같은 경우에는 `state_checked` 속성을 사용하는 것이 적합할 것 같습니다 :)

2023-05-23 08:03 UTC, b1urrrr commented on app/src/main/res/drawable/ic_back.png
png는 기기에 따라 픽셀이 깨져보일 수 있기 때문에 이미지들은 피그마에서 svg 파일로 추출하여 vector asset으로 추가하는 것이 좋을 것 같습니다!

2023-05-23 08:03 UTC, b1urrrr commented on app/src/main/res/layout/activity_dm.xml
> +                android:id="@+id/ll_dm"
```suggestion
            <LinearLayout
                android:id="@+id/layout_dm"
```
[xml id 컨벤션](https://www.notion.so/go-sopt/xml-id-4991afbaf2564686bcb1953fc9341376) 확인 부탁드립니다! 다른 컴포넌트들도 한번씩 확인해주세요 ㅎㅎ

2023-05-23 08:03 UTC, b1urrrr commented on app/src/main/res/layout/activity_dm.xml
> +                    android:layout_width="wrap_content"
요 컴포넌트는 id 속성이 빠진 것 같습니다!

2023-05-23 08:03 UTC, b1urrrr commented on app/src/main/res/layout/item_dm_message.xml
> +        app:layout_constraintTop_toTopOf="@+id/tv_dm_msg_name" />
터치가 가능한 컴포넌트에는 touch target의 용도로 padding 12dp를 지정해주는 것이 좋습니다!

2023-05-23 08:13 UTC, b1urrrr commented
> 스토리뷰 동그라미 ui가 xml (selector 이용) 을 재사용한다는게 맞나요??

넵 스토리뷰의 프로필 이미지에 대한 drawable 파일은 재사용하는 것이 효율적입니다! 그런데 생각해보니 스토리뷰에 사용되는 drawable은 스토리가 없는 경우, 스토리가 있는 경우, 스토리가 있는 친한 친구인 경우, 스토리를 읽은 경우 이렇게 네 가지가 존재하기 때문에 selector를 사용할 수 없을 것 같습니다! 따라서 drawable 4개를 만들어 재사용하면 될 것 같네요

2023-05-23 09:55 UTC, SeonHwan-Kim approved these changes
코리할게 안보입니둥..

2023-05-23 09:55 UTC, SeonHwan-Kim commented on app/src/main/res/layout/activity_dm.xml
> +                        android:id="@+id/btn_dm_newdm"
iv_dm_newdm!!

2023-05-23 09:55 UTC, SeonHwan-Kim commented on app/src/main/res/layout/activity_dm.xml
> +                    android:text="메시지"
string.xml로 빼줘도 좋을 것 같아용

2023-05-23 14:08 UTC, minju1459 commented on app/src/main/AndroidManifest.xml
> +            android:name=".ui.main.dm.DmActivity"
manifest 관리가 항상 헷갈렸는데 좋은 꿀팁 감사합니다!!

2023-05-23 14:09 UTC, minju1459 commented on app/src/main/java/com/sopt/instagram/ui/main/dm/GetStoryAdapter.kt
> +            }
앗 그렇군요 ! 그럼 고유한 값이 두개라면 둘 다 return하는 방식이 맞을까요..!?

2023-05-23 14:11 UTC, minju1459 commented on app/src/main/res/drawable/ic_back.png
항상 png로 넣으면 깨져서 고민이었는데 이제부터 적용해보겠습니다!

2023-05-23 14:12 UTC, minju1459 commented on app/src/main/res/layout/activity_dm.xml
> +                    android:text="메시지"
앗 놓친 부분이네요  바로 적용하겠습니다~!

2023-05-23 18:51 UTC, b1urrrr commented on app/src/main/java/com/sopt/instagram/ui/main/dm/GetStoryAdapter.kt
> +            }
> 앗 그렇군요 ! 그럼 고유한 값이 두개라면 둘 다 return하는 방식이 맞을까요..!?

두 값을 비교한 boolean 결과를 반환하도록 구현해도 괜찮습니다!

2023-05-24 17:21 UTC, b1urrrr approved these changes
LGTM 👍💚

2023-05-24 17:38 UTC, merged